FROM openjdk:11-jdk-slim

ENV APP_HOME=/usr/apps

ENV APP_PORT_DEV=8080

ARG SPRING_DATASOURCE_URL

ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}

WORKDIR $APP_HOME

COPY target/*.jar app.jar

EXPOSE $APP_PORT_DEV

CMD java -jar app.jar --SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
