name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Qwerty_123!#
          MYSQL_DATABASE: demo
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CI ongoing... :eyes:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Specify the Java distribution
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Wait for MySQL to be ready
        run: |
          for i in `seq 1 30`; do
            if mysql -h 127.0.0.1 -P 3306 -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1' > /dev/null 2>&1; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-maven

#      - name: Build with Maven
#        run: mvn clean package -e -X

      - name: Run tests
        run: mvn test -e -X 2>&1 | tee test-output.log
        continue-on-error: true
        id: test-step

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Read test log
        if: steps.test-step.outcome == 'failure'
        id: read-log
        run: cat test-output.log

      - name: Send Slack notification on test failure
        if: steps.test-step.outcome == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: failure()
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: |
            :x: Test step failed
            \`\`\`
            ${{ steps.read-log.outputs.content }}
            \`\`\`
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Build Docker image
        if: success() && steps.test-step.outcome == 'success'
        run: docker build . -t mirfanduri/springboot-mysql-slack-githubaction:${{ github.sha }}

      - name: Log in to Docker Hub
        if: success() && steps.test-step.outcome == 'success'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        if: success() && steps.test-step.outcome == 'success'
        run: docker push mirfanduri/springboot-mysql-slack-githubaction:${{ github.sha }}

      - name: Send Slack notification on success
        if: success() && steps.test-step.outcome == 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: success()
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':tada: Build successful!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Always notify Slack at the end
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':x: CI finished with status: ${{ job.status }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
